sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: itqXkYtCfTXp2dFGS+GE0fosCnVn2VwNP5GdEJZlL4pE4CoZI1eT5aBlV2SVWl2uo0IMuQBUTE8oTAMyHixj0LMiW69vAlR4cpaE4V4vJ8xi9V2Y0QGNN1EgtrDiwXlwetYfgMz7Ci9753ebTLuUT/gMY+YlGBicRqAtma9lPSLhhQYE/rSIAYYXNj+Wn/a+G2bu+y0Jf2rK22Nrno0gklJ+IIcJgoEf/TlNy9JkCg0mqNMElAmi5Jleob9yZo3oCWqjbL3dos7deA5aNBWTVB15m0taU8r3op8ybIKO6MBsJPa/JgV9JTXtM5iWeoAnk3zqhTmqjecrDvJzkGbCu+4gHy/aeOSS1y5fEIGNJD+qdKQasLxsOd5QcS1QlEDCY4+dUJYOCOclwOxeafgXjmoPvwacyh9x35FC2ar9G8rEG5uUlVhWEebk9BT7nF+GGmxaAwX0dvDigOg0YUixXyqRxchRhglAWFw5P8E1pN0VIxOSFi7PdM+p9H7JOsCBTyldKH9diLoZNqBXNaJNZ6J04lQv4deKT31gJmUQENFsru0exmoAOv41P47mEU1wRDzXLlizC+eDXbD7epA5RyG0zwEgDi692+wsqe9FBmS3mda0eCHnwy18JUTkqb+e7lccJMJSvhGp0JfY56ODrPCI6b782ChXLnGxf+y5070=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Jeanne-of-the-Marshes_4233
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy